/**
 * The exercise catalogue: about five hundred exercises the app does not carry as database rows.
 * An entry becomes an Exercise only when the owner adds it or a quick session uses it; until then
 * it is data beside the database. Generated by scripts/build-exercise-catalogue.mjs.
 *
 * Pure: no IO. The lazy loaders for the data files are in src/data/catalogue.ts.
 */
import type { Equipment, Exercise, ExerciseKind, MuscleGroup } from './types';

export interface CatalogueEntry {
  /** Lowercase, hyphenated, unique; names the entry's picture folder. */
  slug: string;
  /** The dataset's own name, verbatim. */
  name: string;
  muscleGroup: MuscleGroup;
  equipment: Equipment;
  kind: ExerciseKind;
  isCompound: boolean;
  unilateral: boolean;
  level: 'beginner' | 'intermediate' | 'expert';
}

/** `Exercise.demo` for a catalogue exercise: this prefix and the slug. Also the picture key and the dedupe key. */
export const CATALOGUE_DEMO_PREFIX = 'cat:';
export const CATALOGUE_FRAME_COUNT = 2;

export function catalogueDemoKey(slug: string): string {
  return CATALOGUE_DEMO_PREFIX + slug;
}

export function isCatalogueDemo(demo: string | undefined): demo is string {
  return demo !== undefined && demo.startsWith(CATALOGUE_DEMO_PREFIX) && demo.length > CATALOGUE_DEMO_PREFIX.length;
}

/** The slug behind a catalogue demo key; '' for a key that is not one. */
export function catalogueSlugOf(demo: string): string {
  return isCatalogueDemo(demo) ? demo.slice(CATALOGUE_DEMO_PREFIX.length) : '';
}

/** Where the build puts a frame (frames are 1-based). */
export function catalogueFrameUrl(slug: string, frame: 1 | 2): string {
  return `/catalogue/${slug}/${frame}.webp`;
}

/** Groups whose exercises count as lower body (the leg-day protein target reads this). */
export const LOWER_BODY_GROUPS: ReadonlySet<MuscleGroup> = new Set<MuscleGroup>(['quads', 'hamstrings', 'glutes', 'calves', 'adductors']);

const SMALL_JOINT_GROUPS: ReadonlySet<MuscleGroup> = new Set<MuscleGroup>(['biceps', 'triceps', 'shoulders']);

function restFor(e: CatalogueEntry): number {
  if (e.kind === 'carry') return 90;
  return e.isCompound ? 150 : 75;
}

function incrementFor(e: CatalogueEntry, lowerBody: boolean): number {
  if (e.kind === 'bodyweight_plus') return 2.5;
  switch (e.equipment) {
    case 'dumbbell':
      return !e.isCompound && SMALL_JOINT_GROUPS.has(e.muscleGroup) ? 1 : 2;
    case 'machine':
      return 5;
    case 'cable':
      return SMALL_JOINT_GROUPS.has(e.muscleGroup) ? 2.5 : 5;
    case 'barbell':
      return lowerBody ? 5 : 2.5;
    case 'kettlebell':
      return 2;
    default:
      return 2.5;
  }
}

/** The Exercise row a catalogue entry becomes. The caller supplies `id` and `createdAt`. */
export function exerciseFromCatalogue(e: CatalogueEntry): Omit<Exercise, 'id' | 'createdAt'> {
  const isLowerBody = LOWER_BODY_GROUPS.has(e.muscleGroup);
  return {
    name: e.name,
    kind: e.kind,
    muscleGroup: e.muscleGroup,
    isCompound: e.isCompound,
    isLowerBody,
    defaultRestSec: restFor(e),
    defaultIncrement: incrementFor(e, isLowerBody),
    unilateral: e.unilateral,
    equipment: e.equipment,
    demo: catalogueDemoKey(e.slug),
  };
}

/** True when `token` starts a word of `text` (a word begins at the start or after a non-alphanumeric). */
function startsWord(text: string, token: string): boolean {
  for (let i = text.indexOf(token); i !== -1; i = text.indexOf(token, i + 1)) {
    if (i === 0 || !/[a-z0-9]/.test(text[i - 1])) return true;
  }
  return false;
}

/**
 * How well a query's words match one thing: 0 when its name starts with the whole query, 1 when
 * every word starts a word of the name, 2 when every word is somewhere in the name, 3 when the
 * words are found only through the rest of `haystack` (muscle group, equipment), and null when a
 * word is nowhere (or there are no words). `name` and `haystack` are lowercase, and `haystack`
 * holds the name too. The catalogue search and the exercise list both rank by this, so a word
 * means the same in each.
 */
export function matchTier(tokens: readonly string[], name: string, haystack: string): number | null {
  if (tokens.length === 0) return null;
  if (!tokens.every((t) => haystack.includes(t))) return null;
  if (name.startsWith(tokens.join(' '))) return 0;
  if (tokens.every((t) => startsWord(name, t))) return 1;
  if (tokens.every((t) => name.includes(t))) return 2;
  return 3;
}

/**
 * Entries whose name, muscle group or equipment contains every word of `query`, best first: the
 * name starts with the query, then every word starts a word of the name, then every word is
 * somewhere in the name, then the ones that matched through muscle group or equipment. Ties go
 * alphabetically. An empty query returns nothing (the caller shows no list until the owner types).
 */
export function searchCatalogue(entries: readonly CatalogueEntry[], query: string, limit = 30): CatalogueEntry[] {
  const tokens = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (tokens.length === 0 || limit <= 0) return [];

  const ranked: { entry: CatalogueEntry; tier: number; name: string }[] = [];
  for (const entry of entries) {
    const name = entry.name.toLowerCase();
    const tier = matchTier(tokens, name, `${name} ${entry.muscleGroup} ${entry.equipment}`);
    if (tier === null) continue;
    ranked.push({ entry, tier, name });
  }
  ranked.sort((a, b) => a.tier - b.tier || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0) || (a.entry.slug < b.entry.slug ? -1 : 1));
  return ranked.slice(0, limit).map((r) => r.entry);
}
