/**
 * The bundled UK food table: CoFID 2021 (McCance and Widdowson's Composition of Foods Integrated
 * Dataset), plus a curated layer of everyday ingredient names mapped to CoFID codes.
 *
 * `src/data/ukFoodTable.json` (~2,850 foods) and `src/data/ukFoodAliases.json` (~100 aliases) are
 * generated by `scripts/uk-food-table.py`, run by hand against the CoFID spreadsheet — see that
 * script's header for the licence, the source URL and how rows and aliases were chosen. Neither
 * JSON file is hand-edited.
 *
 * The two interfaces below (`TableFood`, `FoodAlias`, `FoodUnit`) are the structural shape shared
 * with `src/domain/ingredientMatch.ts`, kept here as local copies rather than an import so this
 * data module and the pure domain module do not depend on each other.
 */

import type { Macros } from '@/domain/food';

export interface TableFood {
  code: string;
  name: string;
  per100: Macros;
}

/** A count-style serving, e.g. one egg. `grams` is always an app estimate — see the alias JSON's
 * `unitSource` and the generating script's header for why no licensed weight table exists. */
export interface FoodUnit {
  label: string;
  plural: string;
  grams: number;
}

/** Plain lower-case names (e.g. `['egg', 'eggs']`) that all resolve to one CoFID code. */
export interface FoodAlias {
  words: string[];
  code: string;
  unit?: FoodUnit;
}

export interface UkFoodTable {
  foods: TableFood[];
  aliases: FoodAlias[];
}

export const UK_FOOD_TABLE_ATTRIBUTION: { name: string; url: string; licence: string } = {
  name: "McCance and Widdowson's Composition of Foods Integrated Dataset (2021)",
  url: 'https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid',
  licence:
    'Open Government Licence v3.0 — Contains public sector information licensed under the Open Government Licence v3.0.',
};

let tablePromise: Promise<UkFoodTable> | null = null;

/**
 * Loads the UK food table and its alias layer. Both JSON files are dynamically imported, so
 * neither is in the app's first-paint bundle — only a screen that actually needs the table (the
 * recipe builder) pulls them in. The result is memoised: the JSON is fetched and parsed once per
 * page load, however many times this is called.
 */
export async function loadUkFoodTable(): Promise<UkFoodTable> {
  if (!tablePromise) {
    tablePromise = Promise.all([
      import('./ukFoodTable.json') as Promise<{ default: { foods: TableFood[] } }>,
      import('./ukFoodAliases.json') as Promise<{ default: FoodAlias[] }>,
    ]).then(([table, aliases]) => ({
      foods: table.default.foods,
      aliases: aliases.default,
    }));
  }
  return tablePromise;
}
